### ISSUE TITLE
Add timeline

### ISSUE THREAD

**Issue by KTibow** [bachya/simplisafe-python#121]
**Is your feature request related to a problem? Please describe.**
When you open SimpliSafe's app or webpage, you can click to see a timeline with past events.

**Describe the solution you'd like**
I'd like a way to do something like get_events() and get past timeline activities.

**Additional context**

- I'm not sure if there's a difference between events and the timeline, but I'm pretty sure they're different because events get cleared and the timeline doesn't.
- Later on, it might be useful to download associated videos.

**Comment by bachya** [comment]
`system.get_events()` utilizes the same underlying API as SimpliSafe's `Timeline` view. You can retrieve past events by altering the `from_timestamp` parameter: https://simplisafe-python.readthedocs.io/en/latest/system.html#events

Downloading associated videos will likely be a part of what solves https://github.com/bachya/simplisafe-python/issues/85.
