### ISSUE TITLE
Find new websocket event types

### ISSUE THREAD

**Issue by bachya** [bachya/simplisafe-python#144]
We need the community's help to identify how various events (disarming the system, camera motion, etc.) are represented in SimpliSafe's unofficial websocket API.

# What We Have So Far

* 1110: `alarm_triggered`
* 1120: `alarm_triggered`
* 1132: `alarm_triggered`
* 1134: `alarm_triggered`
* 1154: `alarm_triggered`
* 1159: `alarm_triggered`
* 1162: `alarm_triggered`
* 1170: `camera_motion_detected`
* 1301: `power_outage`
* 1350: `connection_lost`
* 1381: `sensor_not_responding`
* 1400: `disarmed_by_master_pin`
* 1406: `alarm_canceled`
* 1407: `disarmed_by_remote`
* 1409: `motion_detected`
* 1429: `entry_detected`
* 1458: `doorbell_detected`
* 1531: `sensor_paired_and_named`
* 1601: `user_initiated_test`
* 1602: `automatic_test`
* 1604: `entity_test`
* 3301: `power_restored`
* 3350: `connection_restored`
* 3381: `sensor_restored`
* 3401: `armed_away_by_keypad`
* 3407: `armed_away_by_remote`
* 3441: `armed_home`
* 3481: `armed_away`
* 3487: `armed_away`
* 3491: `armed_home`
* 9401: `away_exit_delay_by_keypad`
* 9407: `away_exit_delay_by_remote`
* 9441: `home_exit_delay`
* 9700: `lock_unlocked`
* 9701: `lock_locked`
* 9703: `lock_error`

# How To Find New Ones

1. Clone the latest version of `simplisafe-python` and `cd` into it:

```bash
$ git clone https://github.com/bachya/simplisafe-python.git
$ cd simplisafe-python/
```

2. Set up and activate a Python virtual environment:

```bash
$ python3 -m virtualenv .venv
$ source .venv/bin/activate
```

3. Initialize the dev environment for `simplisafe-python`:

```bash
$ script/setup
```

4. Open `examples/test_events.py` in a text editor and put your SimpliSafe username and password into lines 11-12, respectively – once you're done, save and close the file:

```python
SIMPLISAFE_EMAIL = "<EMAIL>"  # nosec
SIMPLISAFE_PASSWORD = "<PASSWORD>"  # nosec
```

6. Back on the command line, run `examples/test_events.py`:

```bash
$ python3 examples/test_events.py
```

This will output a big block of JSON that looks like this:

```json
{
    "numEvents": 2,
    "lastEventTimestamp": 1534035861,
    "events": [
        {
            "eventId": 2921814837,
            "eventTimestamp": 1534720376,
            "eventCid": 3401,
            "zoneCid": "0",
            "sensorType": 1,
            "sensorSerial": "123",
            "account": 12345,
            "userId": 12345,
            "sid": 12345,
            "info": "System Armed (Away) by Keypad Garage Keypad",
            "pinName": "",
            "sensorName": "Garage Keypad",
            "messageSubject": "SimpliSafe System Armed (away mode)",
            "messageBody": "System Armed (away mode)",
            "eventType": "activity",
            "timezone": 2,
            "locationOffset": -360,
            "videoStartedBy": "",
            "video": {}
        },
        {
            "eventId": 2920433155,
            "eventTimestamp": 1534702778,
            "eventCid": 1400,
            "zoneCid": "1",
            "sensorType": 1,
            "sensorSerial": "456",
            "account": 12345,
            "userId": 12345,
            "sid": 12345,
            "info": "System Disarmed by Master PIN",
            "pinName": "Master PIN",
            "sensorName": "Garage Keypad",
            "messageSubject": "SimpliSafe System Disarmed",
            "messageBody": "System Disarmed",
            "eventType": "activity",
            "timezone": 2,
            "locationOffset": -360,
            "videoStartedBy": "",
            "video": {}
        }
    ]
}
```

I'm interested in the `eventCid` values for any event that we don't have listed above.

Let me know if you run into trouble. Thanks!

**Comment by jpearce73** [comment]
Can we run that command sequence on a Hassio Raspberry Pi?
From the add on the terminal, there is no Python in the path. 
Can we do it all by ssh into the docker container or do we need to have a completely different development install in order to do this?
I'd like to help but am struggling on how to get started.

**Comment by bachya** [comment]
@jpearce73 I’m not a hass.io expert, unfortunately. I would imagine that SSHing into the appliance would give you access to Python (and would already have `simplisafe-python` installed).

**Comment by jpearce73** [comment]
OK, then maybe I can ask what you develop on and how I can set it up?
I have been trying to figure out how to develop on a Raspberry Pi. I figure that I need to run the testing on the Raspberry Pi, especially when its the thing set up to talk to all the hardware (such as the SimpliSafe). I have been trying to follow the development env setup on the site but I have found its descriptions too generic to follow. Maybe its all assuming its run on a Linux install (which I don't have)

**Comment by bachya** [comment]
@jpearce73 I do my development on my MacBook, but there's no reason you couldn't use a Raspberry Pi. The distinction there is that if you are using hass.io (i.e., you've flashed your Pi's SD card with one of the hass.io images), you're going to have hoops to jump through.

If you have a separate Pi running Raspbian (which is the default OS that people use on those boards), you do, indeed, have a flavor of Linux and everything you need to test/develop. All you need to do is:

* be able to SSH into that device and access a command line
* have Python3 installed
* have Git installed

Once you ensure those steps, you should be able to start with the instructions above. Let me know where you run into trouble and I'll assist!

**Comment by KTibow** [comment]
Still an issue...

**Comment by bachya** [comment]
Saw several new events come from a new installation today:

```
Log Details (WARNING)

Logger: simplipy.websocket
Source: /usr/local/lib/python3.8/site-packages/simplipy/websocket.py:106 
First occurred: 12:52:09 PM (10 occurrences) 
Last logged: 1:05:34 PM

Encountered unknown websocket event type: 1531 ("Sensor Paired and Named 00e43c85"). Please report it at https://github.com/bachya/simplisafe-python/issues.
Encountered unknown websocket event type: 1601 ("User Initiated Test"). Please report it at https://github.com/bachya/simplisafe-python/issues.
Encountered unknown websocket event type: 1604 ("Siren Test"). Please report it at https://github.com/bachya/simplisafe-python/issues.
Encountered unknown websocket event type: 1604 ("Motion Sensor Test"). Please report it at https://github.com/bachya/simplisafe-python/issues.
Encountered unknown websocket event type: 1604 ("Entry Sensor Test"). Please report it at https://github.com/bachya/simplisafe-python/issues.
```

**Comment by bachya** [comment]
Closing this issue per https://github.com/bachya/simplisafe-python/issues/226 – in short, the websocket that this library utilized no longer exists in the unpublished SimpliSafe cloud API.

**Comment by bachya** [comment]
Able to re-open with the introduction of https://github.com/bachya/simplisafe-python/pull/259! 🥳

**Comment by bachya** [comment]
Going to close this in favor of new issues when users discover new websocket event types.
