### ISSUE TITLE
Add social preview

### ISSUE THREAD

**Issue by KTibow** [bachya/simplisafe-python#153]
**Is your feature request related to a problem? Please describe.**
As simplisafe-python becomes bigger, there should probably be a social preview. It boosts popularity in [GitHub Explore](https://github.com/explore) and various social media.

**Describe the solution you'd like**
The image for SimpliSafe's logo should work as long as it has a good license. I think a  centered SimpliSafe logo with some white border should do.

**Additional context**
It might help to use the template for the logo.
This [wikimedia](https://en.m.wikipedia.org/wiki/SimpliSafe#/media/File%3ASimpliSafe_Logo_2018.png) image might work.  
  
Or you could use one of the [existing Home Assistant brand images](https://github.com/home-assistant/brands/tree/master/core_integrations/simplisafe).  
Currently, if somebody shares this on Twitter or Outlook or Facebook or something, you see @bachya's profile picture, instead of the SimpliSafe logo.

**Comment by KTibow** [comment]
This [wikimedia](https://en.m.wikipedia.org/wiki/SimpliSafe#/media/File%3ASimpliSafe_Logo_2018.png) image might work.

**Comment by KTibow** [comment]
How-to: https://help.github.com/en/github/administering-a-repository/customizing-your-repositorys-social-media-preview

**Comment by bachya** [comment]
I’m not sold on the need for this; I’m not looking to “grow” the library, per se. Additionally, I don’t believe I can legally use SimpliSafe’s logo without their express permission.

**Comment by KTibow** [comment]
@bachya got it, sorry. Just if you have spare time.

**Comment by bachya** [comment]
No need to apologize! Appreciate your participation in the project.
