### ISSUE TITLE
Switch to built-in Dependabot

### ISSUE THREAD

**Issue by KTibow** [bachya/simplisafe-python#160]
**Is your feature request related to a problem? Please describe.**
This is an optional option, but [GitHub has acquired Dependabot](https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/), and now there's an option to use **native Dependabot** instead.  
For what I can tell, there's nothing new (except being native), and some special features have been dropped (auto-merge, live dependency updates), but otherwise it has everything and it sounds like this might be interesting to try out.

**Describe the solution you'd like**
The easy way for @bachya to do this is by going to the [Dependabot Dashboard](http://app.dependabot.com/accounts/bachya/), and clicking on the green button next to `simplisafe-python` called `Update config file`.  
Dependabot will make a pull request to switch to native Dependabot.  
Or it's possible to [manually create the `dependabot.yml` file](https://help.github.com/en/github/administering-a-repository/enabling-and-disabling-version-updates#enabling-github-dependabot-version-updates).

**Additional context**
Again, this is 100% optional.

**Comment by bachya** [comment]
Thanks for the thought, @KTibow – since what we have no is working fine (and the native route doesn't add anything material that would help us), I'm going to decline at this time. We can always re-open if new rationale arises.
