### ISSUE TITLE
setup/mfa not asking for username password

### ISSUE THREAD

**Issue by pratheepram** [bachya/simplisafe-python#217]
I tried setting up the simplisafe-python and ran the setup/mfa. but it did not ask for username and password but directly throwed the exception 

xxxx@abcd:~/Projects/simplisafe-python$ script/mfa
Traceback (most recent call last):
  File "script/mfa", line 8, in <module>
    from simplipy.errors import PendingAuthorizationError
ImportError: cannot import name 'PendingAuthorizationError'

**Comment by KTibow** [comment]
Does it work if you run `cd ..` and then run `simplisafe-python/script/mfa`?

**Comment by bachya** [comment]
I just tried with a fresh copy of the `dev` branch and it worked fine. Please confirm that:

1. You have cloned/pulled the up-to-date repo and checked out the `dev` branch
2. You have followed [the setup instructions](https://github.com/bachya/simplisafe-python#contributing)

**Comment by pratheepram** [comment]
Below is the order of commands that i ran.....
  git clone https://github.com/bachya/simplisafe-python.git
  cd simplisafe-python
  script/setup
  script/mfa

The last command immediately gave me this, the documentation says that i will be asked to key in username/password.
  _Traceback (most recent call last):
    File "script/mfa", line 8, in <module>
      from simplipy.errors import PendingAuthorizationError
  ImportError: cannot import name 'PendingAuthorizationError'_

**Comment by bachya** [comment]
The fact that you are already in a virtual env makes me think your `PYTHONPATH` is messed up. Just to check, can you exit it, create a new one for this library, and try the setup again?

**Comment by pratheepram** [comment]
Thanks for all your support. I missed the very first requirement that it requires python 3.7 and greater version. I was using linux mint which had by default python 3.6 only. Installed python 3.8 and created a new venv and worked fine.
