### ISSUE TITLE
Can't create PIN using simplisafe integration.

### ISSUE THREAD

**Issue by veedubb65** [bachya/simplisafe-python#228]
**Describe the bug**
Simplisafe integration can't create or delete PINs.

**To Reproduce**
1. Create an automation like the one below with the following, replacing the system ID with your system ID, and putting the boolean on a lovelace dashboard as a switch. 
```
alias: Simplisafe Enable Guest PIN
description: ''
trigger:
  - entity_id: input_boolean.guest_pin
    from: 'off'
    platform: state
    to: 'on'
condition: []
action:
  - data:
      label: GuestPIN
      pin: 1983
      system_id: 122072
    service: simplisafe.set_pin
mode: single
```
2. Toggle the boolean on, or execute the automation manually.
3. Check simplisafe, and note that it failed to create a PIN
4. Check the Error log, and note that the following new entries exist:
```
Logger: simplipy
Source: /usr/local/lib/python3.8/site-packages/simplipy/api.py:336
First occurred: 3:17:15 PM (4 occurrences)
Last logged: 3:17:30 PM

Error while requesting /ss3/subscriptions/122072/settings/normal: 409, message='Conflict', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/122072/settings/normal?forceUpdate=true') (attempt 1 of 3)
Error while requesting /ss3/subscriptions/122072/settings/pins: 400, message='Bad Request', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/122072/settings/pins') (attempt 1 of 3)
Error while requesting /ss3/subscriptions/122072/settings/pins: 400, message='Bad Request', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/122072/settings/pins') (attempt 2 of 3)
Error while requesting /ss3/subscriptions/122072/settings/pins: 400, message='Bad Request', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/122072/settings/pins') (attempt 3 of 3)Logger: simplipy
Source: /usr/local/lib/python3.8/site-packages/simplipy/api.py:336
First occurred: 3:17:15 PM (4 occurrences)
Last logged: 3:17:30 PM

Error while requesting /ss3/subscriptions/122072/settings/normal: 409, message='Conflict', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/122072/settings/normal?forceUpdate=true') (attempt 1 of 3)
Error while requesting /ss3/subscriptions/122072/settings/pins: 400, message='Bad Request', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/122072/settings/pins') (attempt 1 of 3)
Error while requesting /ss3/subscriptions/122072/settings/pins: 400, message='Bad Request', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/122072/settings/pins') (attempt 2 of 3)
Error while requesting /ss3/subscriptions/122072/settings/pins: 400, message='Bad Request', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/122072/settings/pins') (attempt 3 of 3)
```

```
Logger: homeassistant.components.simplisafe
Source: components/simplisafe/__init__.py:285
Integration: SimpliSafe (documentation, issues)
First occurred: 3:17:33 PM (1 occurrences)
Last logged: 3:17:33 PM

Error during service call: Requesting /ss3/subscriptions/122072/settings/pins failed after 4 tries
```

**Expected behavior**
A new PIN should be created for my SimpliSafe system. This PIN should be named "GuestPIN" and be 1983

**Screenshots**
I'm not sure what screenshots would be of use.

**Additional context**
The goal of this is to have a PIN that can be turned on selectively with a button on a lovelace dashboard, or a scheduled task. Simplisafe doesn't allow schedules for PINs, or temporary PINs, and the process of manually creating a PIN through simplisafe is tedious. Therefor, we use two automations, tied to the same boolean. This one, which creates the PIN when the boolean is switched on, and one that deletes the PIN when the boolean is switched off. 

This used to work, and we used it many times, but had not used it for quite some time before I noticed the problem. I first noticed that it had stopped working sometime in January or early February. My home assistant deployment is fully up to date:

core-2021.4.6
supervisor-2021.04.0
Home Assistant OS 5.13

Through several recent versions I was unable to change any settings through the integration. I noticed a few days ago that at some point I had regained the ability to turn my entry chime on and off, which is accomplished through a similar automation.

**Comment by bachya** [comment]
Thanks for the report, @veedubb65. This has been fixed and [marked for release in the 2021.5.0 version of Home Assistant](https://github.com/home-assistant/core/pull/49962).
