### ISSUE TITLE
Error when running mfa script

### ISSUE THREAD

**Issue by KyleSieb** [bachya/simplisafe-python#236]
Followed all of the steps in the "Accessing the API" section of the documentation, however I get an error when running the mfa script.
<img width="901" alt="Screen Shot 2021-06-05 at 10 55 43 PM" src="https://user-images.githubusercontent.com/33700605/120911304-65a81980-c654-11eb-8c49-9b73144b8e00.png">

**Comment by bachya** [comment]
Just tried the latest `dev` branch and it works fine:

![CleanShot 2021-06-05 at 21 36 05@2x](https://user-images.githubusercontent.com/47216/120911648-2377db80-c646-11eb-89c4-45968a24939d.png)

The "Cannot connect to host" line looks suspect; sounds like your machine can't reach that URL.

**Comment by KyleSieb** [comment]
I'm getting a 401 error when I try connecting to api.simplisafe.com. Do you have any thoughts as to why I'm getting this error?

**Comment by bachya** [comment]
401 general indicates that your username/password is wrong.

**Comment by KyleSieb** [comment]
I tried running the mfa script on my linux machine and didn't run into any issues; must of been some problem with OSX.
