### ISSUE TITLE
Example auth process opens browser with unusable URL

### ISSUE THREAD

**Issue by FlyingDiver** [bachya/simplisafe-python#313]
**Describe the bug**
Example auth process opens browser with unusable URL

**To Reproduce**
Install and attempt to auth using the steps given at:
https://simplisafe-python.readthedocs.io/en/latest/usage.html#accessing-the-api

When the browser opened, the URL was:
com.simplisafe.mobile://auth.simplisafe.com/ios/com.simplisafe.mobile/callback?code=XXXXX

Got this error:
<img width="597" alt="Screen Shot 2022-02-22 at 2 37 48 PM" src="https://user-images.githubusercontent.com/72976/155206212-c1ac8d02-5887-47d7-ad09-35c622b9ff69.png">

Attempted that URL with Chrome as well.  Also did not work.

**Expected behavior**
Web page as in the example doc.

I have a complete console log of the install if you want it.

**Comment by bachya** [comment]
Take a look at the end of step 8 – you've already logged into your account with this browser and SimpliSafe recognizes it, so it's allowing you to skip right to the end. Use the code at the end of the URL and you're good to go.

**Comment by FlyingDiver** [comment]
I can deal with it in my code, but shouldn't the example script be able to detect that and print out the code instead of opening the browser?

**Comment by bachya** [comment]
It is a redirect URL.
