### ISSUE TITLE
generated auth not being stored

### ISSUE THREAD

**Issue by 88gts** [bachya/simplisafe-python#314]
i've been using hardcoded credentials for quite a while, but it appeared to break this morning.

```
Traceback (most recent call last):
  File "state.py", line 45, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "state.py", line 39, in main
    except UnauthorizedError:
NameError: name 'UnauthorizedError' is not defined
```

i updated the env to the latest (including a python update) and am trying to get credentials via a pi4, the browser didn't pop open so i printed out the URL and was able to sign in using the documentation.  unfortunately, safari Network did not show any reference to ErrorPage.html.  i was able to see a token (Tab1) and a code (Tab2) and then generate the token using auth.

```
Press <ENTER> to be taken to the SimpliSafe login page... 
https://auth.simplisafe.com/authorize?audience=httpsXXX
Enter the code received from the SimpliSafe auth webpage: XXXXX

You are now ready to use the SimpliSafe API!
Authorization Code: XXX
Code Verifier: XXXX
```

when trying to test these credentials, i'm getting a failure.  i cant tell if its due the way i grabbed the code or if its pulling from an invalid location.

```
python3 test_client_by_auth.py 
ERROR:root:Invalid credentials
```

**Comment by 88gts** [comment]
i remember i was able to generate a token using "mfa" in an older version, output from that is below.

`simplipy.errors.RequestError: There was an error while requesting /api/token: 404, message='Not Found', url=URL('https://api.simplisafe.com/v1/api/token')`

**Comment by bachya** [comment]
I'm guessing that you're not using the correct code. Look at the end of step 8 in [the docs](https://simplisafe-python.readthedocs.io/en/latest/usage.html#authentication); are you using a code from a url that starts with `com.simplisafe.mobile`?

**Comment by 88gts** [comment]
> I'm guessing that you're not using the correct code. Look at the end of step 8 in [the docs](https://simplisafe-python.readthedocs.io/en/latest/usage.html#authentication); are you using a code from a url that starts with `com.simplisafe.mobile`?

these are the redacted URLs...there's no reference to ErrorPage.html in the Network tab.  
Tab1 (From CLI) = https://auth.simplisafe.com/authorize?audience=https%3A%2F%2Fapi.simplisafe.com%2F&auth0Client=XXX&client_id=XXX&code_challenge=X&code_challenge_method=XX&redirect_uri=com.simplisafe.mobile%3A%2F%2Fauth.simplisafe.com%2Fios%2Fcom.simplisafe.mobile%2Fcallback&response_type=code&scope=offline_access+email+openid+https%3A%2F%2Fapi.simplisafe.com%2Fscopes%2Fuser%3Aplatform
Tab1 (Post Verify) https://tsv.prd.platform.simplisafe.com/v1/tsv/check?token=XXXXX

Tab2 = https://tsv.prd.platform.simplisafe.com/v1/tsv/confirm?code=XXX

**Comment by bachya** [comment]
Assuming you're pulling the code from tab 2, that URL isn't correct. After you successfully authenticate, it should redirect to a `com.simplisafe.mobile` URL, which is where you want to pull the code from. Make sure you're doing this in a desktop browser.

**Comment by 88gts** [comment]
i tried on two different machines (Pi/Chromium and mac/Safari) and the Tab1 URL returns the following HTML after clicking the link in my email.

"Verification Successful
You will be redirected momentarily..."

A redirect never happens, one thing to note is that Safari returns a popup "cannot open the page because the address is invalid."

**Comment by bachya** [comment]
Perhaps try one of the other browsers (Chrome, Edge, Firefox) on your Mac.

**Comment by 88gts** [comment]
i tried on FireFox, still same behavior, Verification Successful but no redirect...

**Comment by 88gts** [comment]
I am also seeing this same redirect issue when using the homebridge-simplisafe3 plugin, perhaps something changed server side.

**Comment by bachya** [comment]
I just tried Mac Safari and it worked as expected, so something environmental must be happening in your setup (especially if it's happening with the Homebridge plugin, too).

**Comment by 88gts** [comment]
hmm, yes you are right.  tried on a third machine and it did the redirect just fine, i was able to generate the code.  i was able to re-auth homebridge, but creds dont seem to be sticking using simplisafe-python.  any ideas?

```
pi@pigts3:/var/www/scripts/simplisafe-python $ sudo python3.8 auth 
Press <ENTER> to be taken to the SimpliSafe login page... 
Enter the code received from the SimpliSafe auth webpage: XXXX

You are now ready to use the SimpliSafe API!
Authorization Code: XXX
Code Verifier: XXX
```
```
pi@pigts3:/var/www/scripts/simplisafe-python $ cat test2.py 
import asyncio

from aiohttp import ClientSession
import simplipy


async def main() -> None:
    """Create the aiohttp session and run."""
    async with ClientSession() as session:
        simplisafe = await simplipy.API.async_from_auth(
            "<AUTHORIZATION_CODE>",
            "<CODE_VERIFIER>",
            session=session,
        )

        # Sometime later:
        new_simplisafe = await simplipy.API.async_from_refresh_token(
            simplisafe.refresh_token,
            session=session,
        )

        # ...


asyncio.run(main())
```
```
pi@pigts3:/var/www/scripts/simplisafe-python $ sudo python3.8 test2.py 
Traceback (most recent call last):
  File "/var/www/scripts/simplisafe-python/simplipy/api.py", line 99, in async_from_auth
    token_resp = await api._async_request(
  File "/var/www/scripts/simplisafe-python/simplipy/api.py", line 248, in _async_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1000, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('https://auth.simplisafe.com/oauth/token')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test2.py", line 25, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 608, in run_until_complete
    return future.result()
  File "test2.py", line 10, in main
    simplisafe = await simplipy.API.async_from_auth(
  File "/var/www/scripts/simplisafe-python/simplipy/api.py", line 114, in async_from_auth
    raise InvalidCredentialsError("Invalid credentials") from err
simplipy.errors.InvalidCredentialsError: Invalid credentials
```

**Comment by bachya** [comment]
That exception is getting thrown in `simplipy.API.async_from_auth`, so you are providing a verifier/code combo that is incorrect.

**Comment by 88gts** [comment]
can you tell me where the verifier/code should be stored so i can verify it is being saved correctly? i am generating the code without issue now but i believe the issue is where the script is storing the token.

**Comment by bachya** [comment]
This values don't get stored for security reasons; they are "exchanged" for an access token that lasts 1 hour and a refresh token that can be used to generate a new access/refresh token pair. Unfortunately, that's not occurring in your case because the exchange is invalid.

99% of the time when this occurs, an incorrect `code` is being used. You're certain you're using the code at the very end of the `com.simplisafe.mobile` URL (excluding the equal sign that precedes it)?

**Comment by 88gts** [comment]
i made progress, i didn't realize i had to store the auth code and verifier into the "test_client_by_auth" script, which succeeded. i incorrectly assumed the auth script generated a token.  it ran the first time, but obviously the second time failed due to it being a one time use code.

do you have an example where i can use this auth and verifier once, but generate the refresh token each time to poll the system for status?

**Comment by bachya** [comment]
If the library is continually running, refreshing the token will happen automatically under the hood. I'm assuming that's not your use case – and that you are running one-off executions every so often – but including this info just in case.

There is an example of how `async_from_refresh_token` works in the docs: https://simplisafe-python.readthedocs.io/en/latest/usage.html#refreshing-the-access-token

Note that although you can, you shouldn't refresh the token on every poll; the access token should be good for one hour. It would be better to get a token, store the datetime it expires, and if you're past that window in the next run, only refresh theme.

**Comment by 88gts** [comment]
you are correct, i am polling the system periodically, it is not constant.  forgive my ignorance, it was easier to do this using credentials, the tokens are throwing me for a loop :)

so i can successfully auth using async_from_auth() and the one time auth code/verifier.  i understand i need to use a refresh token thereafter.  if i look at test_client_by_refresh_token, it is expecting a SIMPLISAFE_REFRESH_TOKEN.  i am not sure how to generate that initially.  if i use your example for "Refreshing the Access Token" i would need to pass in the code/verifier which expire each time, which obviously expires.  

maybe to help with the goal, im just polling for system status once an hour (or more) and can write the code to generate the token hourly, but still not sure how to get it and pass it initially.

again, thanks for the patience and help.

**Comment by bachya** [comment]
Once you successfully call `async_from_auth`, you will have an authenticated `API` object; this object holds the tokens as properties of itself. Details: https://simplisafe-python.readthedocs.io/en/latest/advanced.html#the-simplisafe-object

**Comment by 88gts** [comment]
Excellent. I have everything I need.  Thanks for the guidance, I guess I need to figure out why my systems wouldn't resolve the link but glad it is all working now.
