### ISSUE TITLE
Cameras??

### ISSUE THREAD

**Issue by graanco** [bachya/simplisafe-python#32]
Did you happen to find the address for the cameras. I found the APIconfigs and it has media listed...

**Comment by graanco** [comment]
I seen the same recently and it was add into todays patch... I've been asking around for a link... nothing back yet. I did tear apart the SWF file and didn't see anything simple. I might need to do a proxy server.

**Comment by bachya** [comment]
I don’t have access to a camera for testing, unfortunately.

**Comment by graanco** [comment]
https://media.simplisafe.com/v1/{UUID}/flv \
  -H 'Accept: application/json' \
  -H 'Authorization: Bearer {token}'
Someone found the code... here it is...

**Comment by bachya** [comment]
That won't help me build working functionality. If you have a camera for testing and want to take a stab implementing it, feel free to add a PR.

**Comment by graanco** [comment]
Well then... how good are you with socket.io??? It looks like SimpliSafe uses that to push status updates... I can't seem to figure out how to make it work via nodejs. I have a feeling it has something to do with the WebSocket connecting security. I think it is set through the website that part automatically. And oh yes this is SimpliSafe API is in Angular.
  https://webapp.simplisafe.com/res/components/ss-control-panel/1.30.1/ss-control-panel.js
Socket.io is pulled from 
 https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.5.1/socket.io.min.js
and it uses this API
 https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.5.1/socket.io.js

**Comment by bachya** [comment]
If you need to talk to a SocketIO server with this library, you can always consider https://github.com/miguelgrinberg/python-socketio.

**Comment by graanco** [comment]
Good thought but what I see it socket.io will not connect since it isn't getting passed the https security to websocket security... Their connection at SimpliSafe is using wss:// and https:/// first calls website then upgrade from https to wss. What I can tell many clients, I've tried isn't passing the TLS... Also the site that they grab the socket.io from also calls into another JS file for the WebSocket calls... Very strange and kind of hard to reverse engineer.... I am almost ready to create my own WebSocket just to access the api pushes...
