### ISSUE TITLE
syntax error when I : import simplipy

### ISSUE THREAD

**Issue by maxcli** [bachya/simplisafe-python#354]
here is a partial snippet . Notice I had to add commas . 
I get a error : Exception has occurred: SyntaxError invalid syntax.

simplisafe-python
async def main() -> None:

    async with ClientSession() as session:
        api = await simplipy.API.async_from_credentials(
            "secret1",
             "secret2",
            session=session,
        )

asyncio.run(main())

**Comment by bachya** [comment]
Please post the entire script; your snippet doesn't include any imports.

**Comment by maxcli** [comment]
`import asyncio #<--dies here

from aiohttp import ClientSession
import simplipy


async def main() -> None:
    """Create the aiohttp session and run."""



    async with ClientSession() as session:
        api = await simplipy.API.async_from_credentials(
            "peter.clift@gmail.com",
             "Around@2go",
            session=session,
        )


asyncio.run(main())`

**Comment by bachya** [comment]
If the script dies at `import asyncio`, the issue is with your environment (and not this library).

**Comment by maxcli** [comment]
Correction. I meant to say it dies on  line 4 
 import simplipy

**Comment by maxcli** [comment]
here is a screen shot 

https://imgur.com/cv6vhmd

**Comment by bachya** [comment]
[Line 41 of `simplipy/api.py`](https://github.com/bachya/simplisafe-python/blob/f2be7e03cf155845b9e5ee0dcb2a45c9e175ed77/simplipy/api.py#L38-L41) doesn't have a syntax error; as I mentioned, the example script included in this repo works fine.

* What OS are you on?
* How did you install `simplipy`?
* What version of Python are you using?

**Comment by bachya** [comment]
I took a closer look at your screenshot:

![image](https://user-images.githubusercontent.com/47216/173134748-ce598255-bbc4-4ccf-998f-f6f028a25e5e.png)

The error doesn't reference `simplipy/api.py` – it references `simplipy.py`, which isn't a file in this library. You likely created that file in the same directory (or somewhere else in your Python path); `simpli1.py` is trying to import that file, not this library.

**Comment by maxcli** [comment]
Yes, I had a file called simplipy.py  - Sorry for wasting your time  !
 I've been programmer since 1980 non-stop  , and I still make silly mistakes.

**Comment by bachya** [comment]
No worries! I do, too, and helping each other is what's great about open-source. 👍🏻
