### ISSUE TITLE
What to do about expired certs?

### ISSUE THREAD

**Issue by bentwookie** [bachya/simplisafe-python#361]
Howdy, I'm trying to run the test_client_by_credentials.py example. This call:

```
            simplisafe = await API.async_from_credentials(
                SIMPLISAFE_USERNAME,
                SIMPLISAFE_PASSWORD,
                session=session,
            )
```
Is failing with: 
`ERROR:root:Error while determining the Auth0 login URL: Cannot connect to host auth.simplisafe.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)')]`

I believe my username and password are specified correctly. Anyone else having trouble with their cert?

**Comment by bentwookie** [comment]
I can pass in ssl:false at the request call site and get through, but that seems suboptimal.

**Comment by bachya** [comment]
I just ran that same script without issue, so I don't think there's a systemic issue.

> I can pass in ssl:false at the request call site and get through, but that seems suboptimal.

Agreed: possible, but definitely not preferred.

**Comment by bentwookie** [comment]
The Home Assistant integration (which might even use your code for all I know) worked ok from a different machine. Maybe something funky about how I setup the venv? I'll have to poke at it.

**Comment by bachya** [comment]
> The Home Assistant integration (which might even use your code for all I know) worked ok from a different machine.

I'm the author of that integration and it does, indeed, use this library. 😎 Keep me posted if you find anything!

**Comment by bachya** [comment]
@bentwookie Are you still experiencing this?

**Comment by bentwookie** [comment]
Yeah. If I remove my ssl=false parameters, it fails the same way it did the other day. The HA side is still working great.

**Comment by bachya** [comment]
If it's working from your Home Assistant machine, all signs point to something on your local machine. Depending on the operating system, perhaps you need to update your certificate authority package(s).

Going to close this as not an issue with this library, but if you find more info countering that, please post back here!

**Comment by bentwookie** [comment]
Will do. Thanks for making this BTW. It's been a lot of fun using my Simplisafe switches in HA!
