### ISSUE TITLE
API login fails due to introduction of reCAPTCHA in SimpliSafe's auth flow

### ISSUE THREAD

**Issue by bachya** [bachya/simplisafe-python#370]
Discovered via https://github.com/home-assistant/core/issues/75596. SimpliSafe's login flow now includes reCAPTCHA:

![CleanShot 2022-07-21 at 20 45 49](https://user-images.githubusercontent.com/47216/180351737-1fc13326-607b-4208-8642-e94f3e92724c.png)

...which necessitates the passage of a CAPTCHA-related request body parameter. I don't currently know of a way to determine this from our side, but am investigating.

**Comment by remh** [comment]
yeah i came to the same conclusion. maybe we could iframe the login page instead? is that even doable?

**Comment by bachya** [comment]
In the case of Home Assistant, no – such a solution would be rejected immediately. We may have to go back to a solution where the user logs in via a browser, scrapes the resulting auth token, and pastes that back into HASS.

**Comment by remh** [comment]
makes sense, just had a look it seems pretty straighforward for people who know how to uses the inspector panel but yeah definitely not as friendly as the previous flow.
In the short term, does the HASS plugin support configuration using the access token / bearer token? This would unblock me.
Thank you!

**Comment by bachya** [comment]
> In the short term, does the HASS plugin support configuration using the access token / bearer token? This would unblock me.

Not in any nice, UI-based way, but if you can get a refresh token via your own methods, you can edit your `/config/.storage/core.config_entries` file and input it into the SimpliSafe entry:

```json
{
  "entry_id": "REDACTED",
  "version": 1,
  "domain": "simplisafe",
  "title": "REDACTED",
  "data": {
    "username": "REDACTED",
    "token": "REFRESH TOKEN GOES HERE"
  },
  "options": {},
  "pref_disable_new_entities": false,
  "pref_disable_polling": false,
  "source": "user",
  "unique_id": "REDACTED",
  "disabled_by": null
}
```

Save, then restart HASS – that should allow it to load.

**Comment by remh** [comment]
Thanks unfortunately I don't have an entry in core.config_entries as it's a new setup. I'll wait. Thank you!

**Comment by bachya** [comment]
A "full" `core.config_entries` with _just_ SimpliSafe would look like this:

```json
{
  "version": 1,
  "minor_version": 1,
  "key": "core.config_entries",
  "data": {
    "entries": [
      {
        "entry_id": "REDACTED",
        "version": 1,
        "domain": "simplisafe",
        "title": "REDACTED",
        "data": {
          "username": "REDACTED",
          "token": "REDACTED"
        },
        "options": {},
        "pref_disable_new_entities": false,
        "pref_disable_polling": false,
        "source": "user",
        "unique_id": "REDACTED",
        "disabled_by": null
      }
    ]
  }
}
```

**Comment by remh** [comment]
Yeah I’m just not sure how to generate the entry IDs (or if they just need
to be unique) I’ll look around tomorrow

**Comment by bachya** [comment]
Home Assistant generates config entry unique IDs via [a simple formula](https://github.com/home-assistant/core/blob/dev/homeassistant/util/uuid.py):

```python
"""Helpers to generate uuids."""

from random import getrandbits


def random_uuid_hex() -> str:
    """Generate a random UUID hex.

    This uuid should not be used for cryptographically secure
    operations.
    """
    return "%032x" % getrandbits(32 * 4)
```

(Really, any unique string will do.)

**Comment by bachya** [comment]
Got the expected response from SimpliSafe on Twitter:

<img width="598" alt="CleanShot 2022-07-22 at 07 58 45@2x" src="https://user-images.githubusercontent.com/47216/180455075-0656ec2a-4527-4ce1-8cf2-45a278005f19.png">

So, will move forward with #371.

**Comment by shamoon** [comment]
Wait a minute, did they remove it?!
<img width="446" alt="Screen Shot 2022-08-13 at 7 51 29 AM" src="https://user-images.githubusercontent.com/4887959/184499382-1f21cfa0-12fd-4441-9dde-f1b2a5b91f02.png">
<img width="431" alt="Screen Shot 2022-08-13 at 7 52 50 AM" src="https://user-images.githubusercontent.com/4887959/184499429-f75a674d-9321-4862-81af-5ed6d3a0231d.png">

**Comment by bachya** [comment]
Seeing the same over here... I'm going to give it a week before I consider doing anything. 😂

**Comment by shamoon** [comment]
Ridiculous. Makes their response to you on twitter seem even more dumb. "crucial" 🙄

Agreed will give it a bit of time, I confirmed that reverting to my auto-auth code works again. Ha.
