### ISSUE TITLE
Elaborate usage with HAOS installations

### ISSUE THREAD

**Issue by spospordo** [bachya/simplisafe-python#374]
**Is your feature request related to a problem? Please describe.**
I’m attempting to use this solution with my raspberry pi running Home Assistant OS, however, the installation and usage instructions don’t seem to be written for HAOS since python can not be ran easily through the SSH container.  

**Describe the solution you'd like**
If possible, step by step instructions on how to use this tool with Home Assistant OS. 

**Additional context**
N/A

**Comment by spospordo** [comment]
Yes thank you. I was attempting to re-authenticate an existing simplisafe integration. It looks like the authentication tool only triggers as expected when starting a new integration.

**Comment by bachya** [comment]
Let me know if you have further questions!
