### ISSUE TITLE
Auth script throws `ModuleNotFoundError` on Windows

### ISSUE THREAD

**Issue by Austin1** [bachya/simplisafe-python#377]
So I'm on Windows and I think the instructions are more for OSX/Linux but I've stumbled my way through getting the syntax differences handled for installing all the virtualenv. 

I'm getting 

`
C:\Users\austi\OneDrive\Documents\GitHub\simplisafe-python>py script\auth
Traceback (most recent call last):
  File "C:\Users\austi\OneDrive\Documents\GitHub\simplisafe-python\script\auth", line 8, in <module>
    from simplipy.util.auth import (
ModuleNotFoundError: No module named 'simplipy.util'
`

Any ideas? I've tried pip install simplisafe-python and simplipy

**Comment by bachya** [comment]
It looks like your path isn't set correctly. I'm not a Windows user, so unfortunately, I'm not versed on how Python imports work on Windows.

**Comment by bachya** [comment]
Are you using the Windows Subsystem for Linux (WSL)?

**Comment by Austin1** [comment]
I was not using WSL, but I just tried that and it doesn't interface with the web browser since its running in its own container it can't open the browser. However, it did work that way without a hitch, besides the browser part.

I'm now going to give it one last try using Anaconda. I have no idea why that would work over just a straight terminal in Windows, but worth a shot.

**Comment by bachya** [comment]
Does the URL from which you grabbed the code start with `com.simplisafe.mobile`?

**Comment by bachya** [comment]
FYI, if your using the Home Assistant integration, you shouldn't use the `auth` script – the code verifier isn't the code that gets input into the UI. You'll want to follow these instructions: https://www.home-assistant.io/integrations/simplisafe/#getting-an-authorization-code

**Comment by Austin1** [comment]
Yes those are instructions I've been using and I'm getting the code with the URL mentioned but that is giving error. I ran out of mfa attempts so will try again tomorrow
