### ISSUE TITLE
can't auth using web browser

### ISSUE THREAD

**Issue by 88gts** [bachya/simplisafe-python#390]
my implementation has been up for well over a year but i am having trouble re-authing an expired token. i used to have an old mac laying around that would allow me to generate the com.simplisafe code and auth successfully. i dont have it local.  tried on an regenerating on a brand new mac and on an old Linux setup using Chromium, 56.0.2924.84 Built on Ubuntu 14.04.

Chromium will show an error in the Network console but it seems specific to checking browser capabilities.
 
Failed to set referrer policy: The value 'same-origin' is not one of 'no-referrer', 'no-referrer-when-downgrade', 'origin', 'origin-when-cross-origin', or 'unsafe-url'. The referrer policy has been left unchanged.

checked the docs and remember seeing there were potential issues with this process in the past but i am not sure how to work around it.  i can only use Safari on my new mac per work policy.

**Comment by 88gts** [comment]
found a different web browser that worked, closing.

**Comment by jimbudarz** [comment]
I tried this with both firefox and chromium on ubuntu with no luck.
After I submit my username and password, then submit the 2FA code, `xdg-open` tries to take over and find an appropriate application to open the link. Then when I close the browser and try again, it goes _straight_ to 'xdg-open`.
