### ISSUE TITLE
Add support for the new Smoke+CO Detector

### ISSUE THREAD

**Issue by Abductist** [bachya/simplisafe-python#515]
The new Smoke+CO detector (type 14) should be added to simplipy.device.DeviceTypes. In addition to triggering the same fire (1110) and CO alarm (1162) events that the individual smoke and CO detectors can trigger, this device can also trigger a "pre-alarm" event (1901 with zoneCid == 1 meaning it was triggered and zoneCid == 0 meaning it was cleared) although I'm not sure how beneficial adding that would be.

**Additional context**
The sensor's representation from the `/v1/ss3/subscriptions/{sid}/sensors?forceUpdate=true` endpoint:

```json
{
  "flags": {
    "offline": true,
    "lowBattery": false,
    "swingerShutdown": false
  },
  "serial": "00000000",
  "type": 14,
  "name": "Kitchen",
  "setting": {},
  "status": {
    "coTriggered": false,
    "malfunction": false,
    "tamper": true,
    "lowSensitivity": false,
    "endOfLife": false,
    "test": false,
    "smokeTriggered": false,
    "preSmokeAlarm": false
  },
  "timestamp": 0,
  "rssi": -45,
  "WDTCount": 23,
  "nonce": 0,
  "rebootCnt": 17,
  "deviceGroupID": 0
}
```

**Comment by bachya** [comment]
Thanks, @Abductist. I'm going to hold off on implementing event `1901` for now (until I get a sense that others find it useful), but will put together a PR to add the rest of your info.

**Comment by Abductist** [comment]
That sounds good to me. I appreciate your work on this!
