### ISSUE TITLE
Running in Windows Pure Env

### ISSUE THREAD

**Issue by mydevpeeps** [bachya/simplisafe-python#542]
**Is your feature request related to a problem? Please describe.**
Issues with following the instructions given they assume a unix shell is being used.

**Describe the solution you'd like**
A variation of instructions and/or updated scripts (like activate.ps1) for windows users

**Additional context**
I used these steps to get this to work on Windows 10 Pro in PowerShell without using SQL or unix.

On Windows without WSL these step deviations worked for me...

The files are in slightly different places until you enter the venv on windows... 

NOTE: My python3 is just python and pip and pip3 both work for me .... you may have to use python3 as originally stated in the instructions.

Step 1:
Package requirements are inferred and not specifically called out. You will find out the hard way when you get a module not found error.

If not already installed, additionally requires:

all:
pip install virtualenv pre-commit backoff aiohttp voluptuous

one at a time:
pip install virtualenv
pip install pre-commit
pip install backoff
pip install aiohttp
pip install voluptuous

also needs (but should be installed): async io webbrowser

Step 2:
In a PowerShell prompt be in the ROOT of the simplisafe-python directory. This is important!
Type Scripts/activate.ps1. This will put you into a .venv shell.

Step 3:
Bash shell does not work without WSL so script/setup fails. Run the commands by hand until someone commits a ps1 version of the script files.

pip install poetry
poetry install
pre-commit install

Step 4:
This does not run in windows at all. It can't find the simplypy module because its outside of the scripts path and there were no instructions to tell it to look outside the path.
I get this error when I try to run it with: python script/auth
ModuleNotFoundError: No module named 'simplipy'

Edit script/auth and put this line after the last import:

sys.path.append('/Users/localadmin/PycharmProjects/simplisafe/simplisafe-python')

where the path is where YOU installed the repo.  Save and run script/auth.

**Comment by bachya** [comment]
I am not a Windows user and cannot directly support installation instructions for Windows. If you wish to put together a PR, please do so and I will review.
