### ISSUE TITLE
Add support for socket.io updates from Simplisafe

### ISSUE THREAD

**Issue by aceresia** [bachya/simplisafe-python#59]
Entity updates are delayed when polling.  I see the delay when using the new lock feature or manually arming/disarming the system.  This also slows down automations that depend on those changes.

Subscribing to the socket.io connection that Simplisafe provides for the chrome web client can allow for near real time updates for some events.

**Comment by bachya** [comment]
Thanks for the input.

A more real-time connection has long been my white whale on this project. 😄In the past, an examination of the websocket didn't yield many examples of "actionable events" (the alarm changing states, sensors changing values, etc.). Have you found this to no longer be true?

**Comment by aceresia** [comment]
I've seen arm/disarm, the lock state changes, when the cameras/doorbells turn on (motion), and any sensor that's set to silent alert.

Also, I have some code that get's the connection open and reads the messages in python.  I'm not a good coder, but it could be a place to start.

**Comment by bachya** [comment]
@aceresia Cool! Could you send me examples for each of the scenarios you mentioned? I can absolutely look into a websocket-based method If I have enough data.

**Comment by bachya** [comment]
Experimental support added in #66.
