### ISSUE TITLE
System state enum exception

### ISSUE THREAD

**Issue by maxcli** [bachya/simplisafe-python#630]
**Describe the bug**

 if(state ==   SystemStates.Home) :   <--This line gives error :  AttributeError('Home')

**To Reproduce**

**Expected behavior**
Should be able to compare  system.state with a enum (like HOME,AWAY, OFF)

**Screenshots**

**Additional context**
I have Python3  and Simplisafe  Version:3

This is a sample of my code, which I  copied my code from test_v3.py 

from simplipy.system import SystemStates
... 
state = system.state    <-- equals  SystemStates.HOME 
if(state ==   SystemStates.Home) :  <--Get error  here . AttributeError('Home')

 
here is the traceback :
ERROR:__main__:Traceback (most recent call last):
  File "/home/pi/gitsrc/B9/simpli_sentry.py", line 108, in main
    if(state ==   SystemStates.Home) :
  File "/usr/lib/python3.9/enum.py", line 405, in __getattr__
    raise AttributeError(name) from None

**Comment by maxcli** [comment]
Yes, I reformatted the issue for clarity.

**Comment by maxcli** [comment]
Yes, that was my silly mistake. 
I can return the favor by doing any coding task ( JS, C#, etc).

**Comment by bachya** [comment]
Glad you got it working! I'll close out this issue.
