### ISSUE TITLE
Unable to add Simplipy integration

### ISSUE THREAD

**Issue by cbarham84** [bachya/simplisafe-python#642]
Following all of the instructions step by step, once script/setup runs, after:

Collecting cffi>=1.12 (from cryptography>=2.0->SecretStorage>=3.2->keyring<25.0.0,>=24.0.0->poetry) runs, the script is killed. Then when trying t run script/auth it says "No Module name "simplipy." Unable to get this installed due to that. Not sure if anybody else has had this issue, but I wanted to open an issue just in case.

**To Reproduce**

Following the step by step instructions found here: 
https://simplisafe-python.readthedocs.io/en/latest/usage.html#installation

**Expected behavior**
Expected the script/setup to fully install, allowinme to moveon to script/auth to get a key for the simplisafe integration

**Screenshots**

**Additional context**
I've tried the install multiple times and the script gets killed at the same spot. I am also using the Advanced SSH and Web Terminal Add-on and using putty to access that terminal. I've tried it through the Web UI with the same result also.

**Comment by bachya** [comment]
> I am also using the Advanced SSH and Web Terminal Add-on

Does this indicate you're using Home Assistant OS? You won't be able to manually install this library in that environment (nor do I understand why you'd want to).

**Comment by cbarham84** [comment]
Yes I am, on a Pi 3. I'm not sure how else I would install it in order to retrieve an authorization code for the integration. It's the only thing I could find on it to be perfectly honest...lol

**Comment by bachya** [comment]
The HASS documentation tells you to refer to step 6 of this library's documentation; did you see that? You shouldn't need to manually run `script/auth`.

![CleanShot 2023-10-10 at 08 26 03](https://github.com/bachya/simplisafe-python/assets/47216/bd289262-fd7e-4c7d-99a8-edd8782d2191)

**Comment by cbarham84** [comment]
Yea I sure did. I could never get the com.simplisafe.mobile error to pop up, which is why I went back and did those other steps I trid in Brave and Chrome browsers in a regular tab and an incognito tab. Sorry bud, I know you likely don't have time to be my tech support..haha I appreciate the responses though.

**Comment by cbarham84** [comment]
I was able to get it working. I cleared my cache and went back through the steps and I got the com error and grabbed the code. Thanks for your help.

**Comment by bachya** [comment]
Great! Glad to hear you're off and running.
