### ISSUE TITLE
javascript equivalent of this project?

### ISSUE THREAD

**Issue by tethlah** [bachya/simplisafe-python#643]
**Is your feature request related to a problem? Please describe.**
Not so much a feature request as a general question.

**Describe the solution you'd like**
I’m trying to find something just like this project that’s in javascript so i can use it in node-red.

**Additional context**
I’ve looked all over for a project just like this but in javascript.  I’m running node-red as a Home Assistant addon (home assistant os).  I’m hoping to find something I can use in javascript to create flows for automations based on my alarm status independent of home assistant.  I was thinking that someone here may be able to point me in the right direction.  Even if there’s no javascript library out there, maybe you would know of a developers reference for the simplisafe endpoints or something so I could develop a javascript interface (my knowledge of python is rudimentary at best).  thanks!

**Comment by bachya** [comment]
Although it isn't a drop-in library, the SimpliSafe Homebridge plugin may be worth looking into: https://github.com/homebridge-simplisafe3/homebridge-simplisafe3

**Comment by bachya** [comment]
Not to my knowledge—@shamoon and I have all the endpoints covered in our respective libraries, but that probably isn't what you're looking for.

**Comment by bachya** [comment]
No, and that's crucial: the SimpliSafe API is unofficial. SimpliSafe provides no support of its use; everything we've learned, we've learned on our own.

**Comment by tethlah** [comment]
Gotcha, I see now, you’re both using the same client strings.  Looks like referencing both libraries will probably get me where i’m trying to go, shame no one has done this in node red lol.   Thanks for all the info!

**Comment by shamoon** [comment]
> No, and that's crucial: the SimpliSafe API is unofficial. SimpliSafe provides no support of its use; everything we've learned, we've learned on our own.

Yea, they have never given any indication they want to support this kind of stuff, almost seems like the opposite (see: HomeKit, Matter support) 👎

And no, I don’t build the SS api as a separate JS library. We probably should but my focus is elsewhere these days, but I bet you can suss it out from the homebridge plugin, most of the api-related stuff is contained in one place: https://github.com/homebridge-simplisafe3/homebridge-simplisafe3/blob/master/src/simplisafe.js (auth is separated). Feel free to use ofc, attribute as appropriate

**Comment by tethlah** [comment]
Awesome thanks.  Yeah, this is just for personal use, it won't be distributed.  I've done some stuff I thought might be worth putting out there for public consumption, but I don't have the time for active development for those who expect the latest and greatest.  I'm surprised SS isn't being more developer friendly as they seem to have the capability to easily provide it and automation/iot is so prevalent, there's a lot of people who decide what products they want to buy based on the support for integration into their existing systems.

But unless I want to build out my own system that's not supported by local police, options like SS are probably my best bet.
