### ISSUE TITLE
Simplisafe and Home Assistant

### ISSUE THREAD

**Issue by hspindel** [bachya/simplisafe-python#751]
I hope this is the correct plugin for my question.

I have successfully configured Home Assistant so that it recognizes my Simplisafe.  But the only device it shows is the alarm panel.

How do I get the other devices (motion detectors, glass break sensors, door monitors) to be recognized in Home Assistant?

**Comment by bachya** [comment]
Could you post an issue in the Home Assistant Core repo? This repo is just for the underlying library.

https://github.com/home-assistant/core/issues

**Comment by hspindel** [comment]
Thank you for redirecting me!
