### ISSUE TITLE
Unknown websocket event type 1609

### ISSUE THREAD

**Issue by galentx** [bachya/simplisafe-python#822]
2024-06-08 17:52:34.340 WARNING (MainThread) [simplipy] Encountered unknown websocket event type: 1609 ("User-initiated Camera Recording"). Please report it at https://github.com/bachya/simplisafe-python/issues.

Using HomeAssistant integration (HA 2024.5.4 in a docker container). I can probably find the version of simplisafe-python installed if that is necessary.

It may be unrelated, but I stopped receiving event updates in HA from SS about the same time as this error occurred. It took some 'tickling' to get things to work again. Restarting HA didn't seem to fix it but entering a blank Code in the integration "Configure" panel seemed to update all the sensors and allow new events to come through.

**Comment by bachya** [comment]
Still active.
