### ISSUE TITLE
Unable to arm alarm using alarm control panel

### ISSUE THREAD

**Issue by shucktech** [bachya/simplisafe-python#826]
**Describe the bug**
When attempting to arm the system using either the "Arm Home" or "Arm Away" options on the Home Assistant alarm control panel, an error is thrown indicating that arming requires a code, but none was provided. This occurs despite the fact that the correct code is entered into the system.

**To Reproduce**

1. Go to the Home Assistant dashboard.
2. Click on 'Alarm Control Panel'.
3. Select either 'Arm Home' or 'Arm Away'.
4. Observe the error in the Home Assistant logs.
5. Expected behavior
6. The alarm system should arm successfully without errors when the correct code is entered.

Screenshots
![image](https://github.com/bachya/simplisafe-python/assets/1545447/71846c98-6b60-457e-b32f-da3b0f23cf86)

Additional context
This issue started occurring after setting up the SimpliSafe integration in Home Assistant. I've had this working fine in the past, without issue. The error logs specifically mention that "Arming requires a code but none was given for alarm_control_panel.alarm_control_panel", despite the code being correctly provided during the setup of the integration. Attempts to resolve the issue by removing and re-adding the SimpliSafe service have been unsuccessful. The problem has been consistently reproducible across multiple attempts and occurs at the following log entries:

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:283
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 9:03:24 AM (5 occurrences)
Last logged: 9:06:42 AM
Error IDs:

[140309044317632]
[140308437506016]
[140308437510912]
This bug impacts the functionality of the alarm system controls through the Home Assistant interface.

**Comment by shucktech** [comment]
So, I actually found the resolution.

Steps to resolve:

1. Open the control panel, by clicking the "Disarmed" button in the top right of the widget
2. Select the "Settings" cog
3. Enter your auth code generated during setup into the "Default Code" option
![image](https://github.com/bachya/simplisafe-python/assets/1545447/dbe4a7a2-a92b-49d7-8dd8-68b4c9c6ecb1)


I feel like the plugin is not properly setting the code as the "default code" when its setup.

**Comment by bachya** [comment]
This repo is for the `simplisafe-python` library, not Home Assistant. That said, the issue you are reporting has already been fixed and will be released in the next Home Assistant beta.
