### ISSUE TITLE
Can't get past step 2

### ISSUE THREAD

**Issue by paramediccurt** [bachya/simplisafe-python#841]
**Describe the bug**
Step one goes fine.  Step two gets the error in the attached screenshot.

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot 2024-07-09 12 07 24 AM](https://github.com/bachya/simplisafe-python/assets/173751567/8f1b9242-9416-4f68-a967-0c8a9666d24f)

**Additional context**

**Comment by bachya** [comment]
The error indicates that you don't have Python installed on your machine.
