### ISSUE TITLE
Additional WebSocket Return Type

### ISSUE THREAD

**Issue by ssilence5** [bachya/simplisafe-python#87]
The following event types are all described in the SimpliSafe3 Code for HomeBridge for Websockets. I have been using this with HomeBridge and it works really well. Although I am not exhaustively testing it as I do not have a Doorlock, Doorbell, or Cameras.

https://github.com/nzapponi/homebridge-simplisafe3/blob/master/src/simplisafe.js

- 1400, 1407: Alarm Disarmed
 - 1400 is Disarmed by Master PIN
 - 1407 is Disarmed by Remote
- 1406: Alarm Cancelled
- 1409: Motion Event
- 9441: Home Exit Delay
- 3441, 3491: Home Arm
- 9401, 9407: Away Exit Delay
 - 9401 is Away Exit Delay by Keypad
 - 9407 is Away Exit Delay by Remote
- 3401, 3407, 3487, 3481: Armed Away
 - 3401 is Arm Away by Keypad
 - 3407 is Arm Away by Remote
- 1429 is Entry Event
- 1110, 1154, 1159, 1162, 1132, 1134, 1120: Alarm Trigger Event
- 1170: Camera Motion Event
- 1458: Doorbell Event
- 9700: Doorlock Unlocked Event
- 9701: Doorlock Locked Event
- 9703: Doorlock Error Event
- 1602: Automatic Test Event

**Comment by bachya** [comment]
Great info, thank you!
