### ISSUE TITLE
Add support for messages

### ISSUE THREAD

**Issue by bachya** [bachya/simplisafe-python#90]
**Is your feature request related to a problem? Please describe.**
I very irregularly log into either the SimpliSafe web or mobile apps; therefore, I frequently miss messages for things like base station updates.

**Describe the solution you'd like**
I'm not sure what form it would take, but it would be nice if this library offered a way to handle new messages when they are retrieved.

**Additional context**
A response to the `/v1/users/<USER_ID>/subscriptions` endpoint appears to have a messages key:

```json
"messages": []
```

I'm not sure what form messages take in here, but at a minimum, I'm guessing they appear here. Unfortunately, I cleared my most recent message before looking here. 😒 A cursory glance doesn't show any corresponding event over the websocket, so this would have to be part of the REST API.

I'll keep an eye out for future messages.

**Comment by KTibow** [comment]
A SimpliSafe system update was recently sent out, @bachya. Try it now.

**Comment by bachya** [comment]
I don’t see any messages, unfortunately; it’s possible my system hasn’t received it yet, so I’ll keep an eye out.

**Comment by bachya** [comment]
@KTibow I still do not have any new messages from today. If you haven’t already cleared the one you’ve received, let me know and I’ll walk you through how you can assist this issue.

**Comment by KTibow** [comment]
No, I cleared it. If you want to force a message, unplug your base station and plug it  back in.

Sent via Kendell's S7
Get Outlook for Android<https://aka.ms/ghei36>
Or get Outlook for iOS
Or switch to CakeBrowser.com
Or switch to Ecosia.org

________________________________
