### ISSUE TITLE
Request for information: longevity of simplisafe

### ISSUE THREAD

**Issue by Erotemic** [bachya/simplisafe-python#946]
I've been looking at this repo as I try to connect a simplisafe system to home assistant. I'm a fairly competent Python programmer and I'm rapidly learning networking. I am willing to contribute to the project, but I want to see if it could potentially meet my use-case.

I've recently purchased a home that came with an existing simplisafe system. I do want a security system, but I really don't want to be locked into an ecosystem. Thus, I'd like to make use of the hardware that I have (base station, motion sensors, door sensors, glassbreak-detectors, outdoor-camera) and it looks like the current home assistant integration is 80% of the way there. But this isn't about the camera integration per se, I have read that issue thread. 

I'm wondering about the underlying architecture of this tool. I've been able to create an API from a refresh token, and started to play with it, but this makes me worried: if the simplisafe servers go down or if it goes out of business, does this interface fail? Or more generally does the entire simplisafe system fail?

I don't want to depend on anything external for the basic self-monitored system to work, so if the simplisafe hardware is useless without the company I guess I'll need to find new hardware that isn't so proprietary.

However, I _am_ interested in purchasing a monitoring subscription that can respond in an emergency. I already have all the other simplisafe hardware, so if there hardware does work as a standalone system, then I might purchase more of it and buy a simplisafe subscription.

What I'd be really interested in is a monitoring service that would accept hardware from any vendor so long as you could send them the video streams / sensor alerts. It would great if I could use the existing hardware I have with whatever monitoring service I purchase.

**Comment by bachya** [comment]
This open-source library is not officially affiliated with SimpliSafe in any way—unfortunately, I can't provide any data on your questions. Anecdotally, as an SS user, I've found their API (and the integration we've built on top of it) to be reasonably stable. If SS as a company disappears, the API will almost certainly go away, too.

**Comment by Erotemic** [comment]
> If SS as a company disappears, the API will almost certainly go away, too.

That did mostly answer my question, but to clarify: the simplisafe-python package architecture has a step that requires going through the WAN and handshaking with simplisafe servers, and there is no way around this?

Or maybe in other words, even if I have a refresh token, if I unplug my WAN I'm locked out of talking to any of the simplisafe devices?

**Comment by bachya** [comment]
> > If SS as a company disappears, the API will almost certainly go away, too.
> 
> That did mostly answer my question, but to clarify: the simplisafe-python package architecture has a step that requires going through the WAN and handshaking with simplisafe servers, and there is no way around this?
> 
> Or maybe in other words, even if I have a refresh token, if I unplug my WAN I'm locked out of talking to any of the simplisafe devices?

This integration uses SimpliSafe's unpublished cloud API, so it will require internet connectivity between your base station and their cloud.

**Comment by Erotemic** [comment]
Do you think it might be feasible to send packets directly to the WIFI camera, or to the base station in order to interact with the other parts of the system? Has anyone tried doing that wrt to this project? I'm just trying to get a sense of what hacking / reverse engineering / jailbreaking has already been done before I go down roads people have already explored.

**Comment by bachya** [comment]
> Do you think it might be feasible to send packets directly to the WIFI camera, or to the base station in order to interact with the other parts of the system? Has anyone tried doing that wrt to this project? I'm just trying to get a sense of what hacking / reverse engineering / jailbreaking has already been done before I go down roads people have already explored.

That's outside this project's scope. You can do [a quick Google search](https://www.google.com/search?q=simplisafe+reverse+engineering) to see what others say on the subject.
